Repository Kernel360/KDEV3_monicar_FE, pull requests merged in 2025-02, with the labels that each got.

#124 [Feat] RegisterPage API 연동 🌟
  app/(main)/log/[id]/daily/page.tsx
  app/(main)/log/[id]/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/register/styles.css.ts
  app/(main)/log/register/types.ts
  components/common/Breadcrumb/constants.ts
  components/common/Breadcrumb/index.tsx
  components/common/Breadcrumb/types.ts
  constants/api.ts
  lib/apis/interceptors.ts
  lib/apis/notice.ts
  lib/apis/vehicle.ts
  public/www.freepik.com:.webloc
  types/error.ts
Labels: 🪐 API

#128 [Design] PageNotFound 페이지 구현
  .gitignore
  app/not-found.styles.css.ts
  app/not-found.tsx
  lib/apis/interceptors.ts
  package.json
  styles/theme.css.ts
Labels: 🎨 Design

#132 [Fix] Next.js 동적 API 라우트 비동기 처리를 통한 빌드 문제 해결
  app/(main)/dashboard/notice/[id]/page.tsx
Labels: 🐛 Fix

#133 [Feat] 위치조회 > 클러스터링 API 연동 및 기능구현
  app/(main)/location/components/MapSection/index.tsx
  components/domain/map/Map/index.tsx
  constants/map.ts
  hooks/useCurrentMapStatus.ts
  lib/apis/cluster.ts
  lib/apis/vehicle.ts
  lib/utils/map.ts
  lib/utils/normalize.ts
  lib/utils/validation.ts
  types/map.ts
Labels: 🪐 API, ✨ Feat

#135 [Feat] LogPage 기능 구현 🌟
  app/(main)/log/components/ListItem/index.tsx
  app/(main)/log/hooks/useLogData.ts
  app/(main)/log/page.tsx
  app/(main)/log/styles.css.ts
  app/(main)/log/utils/excel.ts
  components/common/ErrorMessage/ErrorMessage.stories.tsx
  components/common/ErrorMessage/index.tsx
  components/common/ErrorMessage/styles.css.ts
  components/domain/vehicle/ControlBar/index.tsx
  components/domain/vehicle/ControlBar/styles.css.ts
  hooks/useData.ts
  lib/utils/validation.ts
Labels: 🪐 API, ✨ Feat

#136 [Fix] Middleware에서 쿠키에 접근하지 못하는 문제 해결
  .gitignore
  lib/apis/interceptors.ts
  middleware.ts
  next.config.mjs
  package.json
Labels: 🐛 Fix

#137 [Fix] 프리뷰 배포 로드 확인용 콘솔 로그 추가
  middleware.ts
Labels: 🐛 Fix

#142 [Feat] 인증 관련 API 연동 및 기능 구현
  app/(auth)/signin/page.tsx
  app/(main)/dashboard/page.tsx
  app/(main)/page.tsx
  app/layout.tsx
  components/layout/AuthGuard/index.tsx
  components/layout/NavBar/index.tsx
  components/layout/NavBar/styles.css.ts
  hooks/useAuth.ts
  lib/apis/auth.ts
  middleware.ts
  stores/useAuthStore.ts
  types/auth.ts
Labels: 🪐 API, ✨ Feat

#143 [Feat] 경로조회 > 기간별 경로 조회 API 연동 및 기능구현
  app/(main)/location/components/MapSection/index.tsx
  app/(main)/location/components/VehicleMarker/index.tsx
  app/(main)/route/RoutePage.tsx
  app/(main)/route/components/MapSection/index.tsx
  app/(main)/route/components/RouteSearchPanel/index.tsx
  app/(main)/route/page.tsx
  hooks/useSearchSingleVehicle.ts
  hooks/useSearchVehicle.ts
  lib/apis/cluster.ts
  lib/apis/route.ts
  lib/apis/vehicle.ts
  lib/utils/normalize.ts
  lib/utils/validation.ts
  mock/vehicleNumberOK.json
  types/map.ts
  types/vehicle.ts
Labels: 🪐 API, ✨ Feat

#141 [Feat] RegisterPage 기능 구현 🌟
  app/(main)/log/register/components/VehicleRegisterForm/index.tsx
  app/(main)/log/register/components/VehicleRegisterForm/styles.css.ts
  app/(main)/log/register/page.tsx
  app/(main)/log/register/styles.css.ts
  app/(main)/log/register/types.ts
Labels: ✨ Feat

#140 [Feat] DetailPage 기능 구현 🌟
  app/(main)/dashboard/components/InspectionStatus/styles.css.ts
  app/(main)/log/[id]/hooks/useDetailData.ts
  app/(main)/log/[id]/hooks/useDetailModal.ts
  app/(main)/log/[id]/hooks/useSearchDate.ts
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/styles.css.ts
  app/(main)/log/[id]/types.ts
  app/(main)/log/[id]/utils/excel.ts
  app/(main)/log/hooks/useLogData.ts
  app/(main)/log/page.tsx
  app/(main)/log/styles.css.ts
  components/common/Modal/index.tsx
Labels: ✨ Feat

#145 [Fix] 쿠키 Domain 수정을 통한 미들웨어 문제 해결
  hooks/useAuth.ts
  lib/apis/client.ts
  middleware.ts
Labels: 🐛 Fix

#148 [Fix] 미들웨어 인증 문제 해결 및 클라이언트 인증 로직 삭제
  app/layout.tsx
  components/layout/AuthGuard/index.tsx
  hooks/useAuth.ts
  middleware.ts
Labels: 🐛 Fix

#149 [Feat] RegisterPage 유효성 검사 로직 추가
  app/(main)/log/page.tsx
  app/(main)/log/register/components/VehicleRegisterForm/index.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/styles.css.ts
  components/common/Message/styles.css.ts
  lib/utils/validation.ts
Labels: ✨ Feat

#150 [FIX] 전역 상태(이메일, 회사명) 새로고침 시 사라지는 문제 해결
  app/(auth)/signin/page.tsx
  app/(main)/dashboard/components/VehicleStatusItem/index.tsx
  app/(main)/dashboard/page.tsx
  app/(main)/location/components/MapSection/index.tsx
  components/layout/NavBar/index.tsx
  hooks/useAuth.ts
  lib/utils/validation.ts
Labels: 🐛 Fix

#151 [Feat] PageLoader 컴포넌트 구현
  app/(main)/dashboard/components/NoticeListBoard/index.tsx
  app/(main)/dashboard/notice/[id]/page.tsx
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/styles.css.ts
  app/(main)/log/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/register/styles.css.ts
  app/(main)/log/styles.css.ts
  components/common/Button/RoundButton/index.tsx
  components/common/PageLoader/index.tsx
  components/common/PageLoader/styles.css.ts
  components/domain/map/Map/index.tsx
Labels: ✨ Feat

#153 [Feat] 내부 테스트를 위한 임시 회원가입 API 연동 및 기능 구현
  app/(auth)/signup/page.tsx
  app/(auth)/signup/styles.css.ts
  lib/apis/auth.ts
  lib/utils/validation.ts
Labels: 🪐 API, ✨ Feat

#155 [Fix] 개별 차량 상세 정보 null 문제 해결
  app/(main)/location/components/VehicleDetailsCard/index.tsx
  app/(main)/route/components/RouteSearchPanel/index.tsx
Labels: 🐛 Fix

#158 [Fix] 미들웨어 인증 로직 개선
  middleware.ts
Labels: 🐛 Fix

#164 [Fix] 대시보드 페이지 닉네임 미출력 버그 수정
  app/(main)/dashboard/components/VehicleStatusPanel/styles.css.ts
  app/(main)/dashboard/page.tsx
  app/(main)/dashboard/styles.css.ts
  components/domain/map/Map/index.tsx
  components/layout/NavBar/NavItem/index.tsx
  components/layout/NavBar/index.tsx
  hooks/useAuth.ts
  lib/apis/interceptors.ts
Labels: 🐛 Fix

#163 [Fix] DatePickerInput 부분 선택 시 API 호출 버그
  app/(main)/log/[id]/hooks/useDetailData.ts
  app/(main)/log/[id]/hooks/useSearchDate.ts
  app/(main)/log/[id]/page.tsx
  components/common/Breadcrumb/constants.ts
  components/common/Breadcrumb/index.tsx
  constants/api.ts
  hooks/useData.ts
  lib/apis/interceptors.ts
  lib/utils/date.ts
Labels: 🐛 Fix

#168 [Style] Dashboard 반응형 작업
  app/(main)/dashboard/components/InspectionStatus/index.tsx
  app/(main)/dashboard/components/InspectionStatus/styles.css.ts
  app/(main)/dashboard/components/NoticeListBoard/styles.css.ts
  app/(main)/dashboard/components/VehicleStatusItem/index.tsx
  app/(main)/dashboard/components/VehicleStatusItem/styles.css.ts
  app/(main)/dashboard/components/VehicleStatusPanel/index.tsx
  app/(main)/dashboard/components/VehicleStatusPanel/styles.css.ts
  app/(main)/dashboard/notice/components/NoticeContent/styles.css.ts
  app/(main)/dashboard/page.tsx
  app/(main)/dashboard/styles.css.ts
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/styles.css.ts
  app/(main)/log/components/ListItem/index.tsx
  app/(main)/log/components/ListItem/styles.css.ts
  app/(main)/log/page.tsx
  app/(main)/log/styles.css.ts
  app/(main)/log/utils/excel.ts
  components/common/Badge/styles.css.ts
  components/common/ControlLayout/styles.css.ts
  components/domain/vehicle/ListHeader/styles.css.ts
  components/layout/NavBar/styles.css.ts
  lib/apis/interceptors.ts
  package.json
  styles/theme.css.ts
  styles/utils.css.ts
  yarn.lock
Labels: 💅🏻 Style

#166 [Fix] 위치조회 페이지 문제 해결
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/(main)/dashboard/page.tsx
  app/(main)/location/components/MapSection/index.tsx
  app/(main)/location/components/VehicleDetailCard/index.tsx
  app/(main)/location/components/VehicleDetailCard/styles.css.ts
  app/(main)/location/components/VehicleMarker/index.tsx
  app/(main)/location/page.tsx
  app/(main)/log/[id]/hooks/useDetailModal.ts
  app/(main)/log/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/route/components/RouteSearchPanel/index.tsx
  components/domain/map/Map/index.tsx
  hooks/useCurrentMapStatus.ts
  hooks/useDisclosure.ts
  hooks/useModal.ts
  hooks/useSearchSingleVehicle.ts
  hooks/useSearchVehicle.ts
  hooks/useVehicleLocationSearch.ts
  lib/apis/cluster.ts
  lib/apis/route.ts
  lib/apis/vehicle.ts
  lib/utils/format.ts
  lib/utils/normalize.ts
  lib/utils/string.ts
  types/map.ts
  types/vehicle.ts
Labels: 🐛 Fix

#183 [Fix] 차량 삭제 기능 제어 및 Breadcrumbs 컴포넌트 구조 개선
  app/(main)/dashboard/notice/[id]/page.tsx
  app/(main)/dashboard/page.tsx
  app/(main)/log/[id]/daily/page.tsx
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/styles.css.ts
  app/(main)/log/[id]/types.ts
  app/(main)/log/components/ListItem/index.tsx
  app/(main)/log/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/styles.css.ts
  components/common/Breadcrumb/Breadcrumb.stories.tsx
  components/common/Breadcrumb/constants.ts
  components/common/Breadcrumb/index.tsx
  components/common/Breadcrumb/types.ts
  components/common/Breadcrumbs/index.tsx
  components/common/Breadcrumbs/styles.css.ts
  types/log.ts
Labels: 🐛 Fix

#184 [Refactor] API 서비스 구조 개선 및 타입 정의 표준화
  app/(main)/dashboard/components/NoticeListBoard/index.tsx
  app/(main)/dashboard/components/VehicleStatusPanel/index.tsx
  app/(main)/dashboard/notice/components/NoticeContent/index.tsx
  app/(main)/location/components/MapSection/index.tsx
  app/(main)/location/components/VehicleDetailCard/index.tsx
  app/(main)/location/components/VehicleMarker/index.tsx
  app/(main)/location/components/VehicleStatusPanel/index.tsx
  app/(main)/location/page.tsx
  app/(main)/log/[id]/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/utils/excel.ts
  app/(main)/route/components/MapSection/index.tsx
  app/(main)/route/components/RouteSearchPanel/index.tsx
  app/(main)/route/page.tsx
  components/domain/map/Map/index.tsx
  hooks/useAuth.ts
  hooks/useData.ts
  hooks/useMapControl.ts
  hooks/useSearchVehicle.ts
  hooks/useVehicleLocationSearch.ts
  lib/apis/auth.ts
  lib/apis/cluster.ts
  lib/apis/index.ts
  lib/apis/interceptors.ts
  lib/apis/notice.ts
  lib/apis/route.ts
  lib/apis/vehicle.ts
  lib/utils/normalize.ts
  types/apis/auth.ts
  types/apis/cluster.ts
  types/apis/route.ts
  types/auth.ts
  types/cluster.ts
  types/error.ts
  types/location.ts
  types/map.ts
  types/notice.ts
  types/route.ts
  types/vehicle.ts
Labels: 🔨 Refactor

#185 [Fix] RegisterPage 버그 수정 및 차량 등록 중복 검사 API 연동
  app/(main)/dashboard/components/NoticeListBoard/styles.css.ts
  app/(main)/dashboard/page.tsx
  app/(main)/dashboard/styles.css.ts
  app/(main)/log/[id]/page.tsx
  app/(main)/log/components/ListItem/styles.css.ts
  app/(main)/log/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/register/styles.css.ts
  app/(main)/log/register/types.ts
  app/(main)/log/styles.css.ts
  lib/apis/vehicle.ts
  lib/utils/validation.ts
Labels: 🐛 Fix, 🪐 API

#186 [Feat] DailyPage API 연동
  app/(main)/log/[id]/daily/components/DailyListItem/index.tsx
  app/(main)/log/[id]/daily/components/HourlyListItem/index.tsx
  app/(main)/log/[id]/daily/components/styles.css.ts
  app/(main)/log/[id]/daily/components/styles/common.css.ts
  app/(main)/log/[id]/daily/hooks/useDailyData.ts
  app/(main)/log/[id]/daily/hooks/useHourlyData.ts
  app/(main)/log/[id]/daily/page.tsx
  app/(main)/log/[id]/daily/styles.css.ts
  app/(main)/log/components/LogListItem/index.tsx
  app/(main)/log/components/LogListItem/styles.css.ts
  app/(main)/log/page.tsx
  app/(main)/log/types.ts
  app/(main)/log/utils/excel.ts
  constants/api.ts
  lib/apis/vehicle.ts
  lib/utils/date.ts
  lib/utils/map.ts
  types/log.ts
Labels: 🪐 API

#192 [Fix] 경로조회 페이지 Suspense 적용해 프리렌더 에러 문제 해결
  app/(main)/route/Route.tsx
  app/(main)/route/components/RouteSearchSection/index.tsx
  app/(main)/route/page.tsx
Labels: 🐛 Fix

#195 [Refactor] 경로조회 > URL 쿼리스트링 기반 데이터 페칭 구현
  app/(main)/route/components/DateRangeSection/index.tsx
  app/(main)/route/components/DateRangeSection/styles.css.ts
  app/(main)/route/components/RouteSearchButton/index.tsx
  app/(main)/route/components/RouteSearchButton/styles.css.ts
  app/(main)/route/components/RouteSearchSection/index.tsx
  app/(main)/route/components/RouteTimelineItem/index.tsx
  app/(main)/route/components/RouteTimelineItem/styles.css.ts
  app/(main)/route/components/RouteTimelineSection/index.tsx
  app/(main)/route/components/RouteTimelineSection/styles.css.ts
  app/(main)/route/components/VehicleSearchSection/indext.tsx
  app/not-found.tsx
  hooks/useQueryParams.ts
  hooks/useVehicleSearch.ts
  lib/apis/route.ts
  lib/utils/normalize.ts
Labels: 🔨 Refactor

#196 [Feat] 차량번호 중복검사 전 입력필드 비활성화 기능 구현
  app/(main)/dashboard/components/Calendar/index.tsx
  app/(main)/dashboard/components/Calendar/styles.css.ts
  app/(main)/dashboard/components/VehicleStatusItem/styles.css.ts
  app/(main)/dashboard/page.tsx
  app/(main)/log/[id]/daily/components/DailyListItem/index.tsx
  app/(main)/log/[id]/daily/components/HourlyListItem/index.tsx
  app/(main)/log/[id]/daily/hooks/useDailyData.ts
  app/(main)/log/[id]/daily/page.tsx
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/styles.css.ts
  app/(main)/log/components/LogListItem/index.tsx
  app/(main)/log/register/page.tsx
  components/common/InspectionStatusAlert/InspectionStatusModal.stories.tsx
  components/common/InspectionStatusAlert/index.tsx
  components/common/InspectionStatusAlert/styles.css.ts
  types/log.ts
Labels: ✨ Feat

#198 [Refactor] URL 쿼리 파라미터 기반 상태 관리 개선
  app/(main)/route/components/DateRangeSection/index.tsx
  app/(main)/route/components/MapSection/index.tsx
  app/(main)/route/components/RouteSearchButton/index.tsx
  app/(main)/route/components/RouteSearchSection/index.tsx
  app/(main)/route/components/RouteTimelineSection/index.tsx
  app/(main)/route/components/VehicleSearchSection/indext.tsx
  app/(main)/route/page.tsx
  components/common/Button/BaseButton/styles.css.ts
  hooks/useVehicleSearch.ts
  lib/apis/vehicle.ts
  lib/services/vehicle.ts
  types/vehicle.ts
Labels: 🔨 Refactor

#199 [Feat] 차량번호 검색 자동완성 기능 구현
  app/(main)/location/Location.tsx
  app/(main)/location/styles.css.ts
  app/(main)/route/components/RouteTimelineSection/styles.css.ts
  components/domain/vehicle/AutoComplete/index.tsx
  components/domain/vehicle/AutoComplete/styles.css.ts
  hooks/useQueryParams.ts
  lib/apis/route.ts
  lib/apis/vehicle.ts
  types/vehicle.ts
Labels: 🪐 API, ✨ Feat

#200 [Design] InspectionPage 퍼블리싱 및 Skeleton 적용
  app/(main)/dashboard/components/Calendar/index.tsx
  app/(main)/dashboard/components/NoticeListBoard/index.tsx
  app/(main)/dashboard/inspection/components/InspectionCard/index.tsx
  app/(main)/dashboard/inspection/components/InspectionCard/styles.css.ts
  app/(main)/dashboard/inspection/components/InspectionStatusItem/index.tsx
  app/(main)/dashboard/inspection/components/InspectionStatusItem/styles.css.ts
  app/(main)/dashboard/inspection/components/InspectionStatusPanel/index.tsx
  app/(main)/dashboard/inspection/components/InspectionStatusPanel/styles.css.ts
  app/(main)/dashboard/inspection/components/Tabs/index.tsx
  app/(main)/dashboard/inspection/page.tsx
  app/(main)/dashboard/inspection/styles.css.ts
  app/(main)/dashboard/page.tsx
  app/(main)/log/[id]/page.tsx
  app/(main)/log/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/types.ts
  components/common/InspectionStatusAlert/InspectionStatusModal.stories.tsx
  components/common/InspectionStatusAlert/index.tsx
  components/common/InspectionStatusAlert/styles.css.ts
  components/common/Skeleton/DetailSkeleton/index.tsx
  components/common/Skeleton/HeaderSkeleton/index.tsx
  components/common/Skeleton/InspectionSkeleton/index.tsx
  components/common/Skeleton/InspectionSkeleton/styles.css.ts
  components/common/Skeleton/LogListItemSkeleton/index.tsx
  components/common/Skeleton/LogListItemSkeleton/styles.css.ts
  components/common/Skeleton/LogSkeleton/index.tsx
  components/common/Skeleton/LogSkeleton/styles.css.ts
  components/common/Skeleton/NoticeSkeleton/index.tsx
  components/common/Skeleton/NoticeSkeleton/styles.css.ts
  components/domain/map/Map/index.tsx
  components/domain/map/MapSkeleton/index.tsx
  styles/theme.css.ts
Labels: 🎨 Design

#204 [Feat] Dashboard Ranking API 연동
  app/(main)/dashboard/components/Calendar/index.tsx
  app/(main)/dashboard/components/Calendar/styles.css.ts
  app/(main)/dashboard/components/InspectionStatus/styles.css.ts
  app/(main)/dashboard/components/Ranking/index.tsx
  app/(main)/dashboard/components/Ranking/styles.css.ts
  app/(main)/dashboard/components/Ranking/useRankingData.ts
  app/(main)/dashboard/page.tsx
  components/common/Skeleton/MapSkeleton/index.tsx
  components/common/Skeleton/RankingSkeleton/index.tsx
  components/common/Skeleton/RankingSkeleton/styles.css.ts
  components/domain/map/Map/index.tsx
  constants/api.ts
  types/vehicle.ts
Labels: 🪐 API

#205 [Feat] 위치조회 차량 검색 자동완성 구현
  app/(main)/dashboard/components/VehicleStatusPanel/index.tsx
  app/(main)/dashboard/inspection/components/InspectionStatusPanel/index.tsx
  app/(main)/location/Location.tsx
  app/(main)/location/components/MapSection/index.tsx
  app/(main)/location/components/VehicleDetailCard/index.tsx
  app/(main)/location/components/VehicleSearchSection/indext.tsx
  app/(main)/location/components/VehicleSearchSection/styles.css.ts
  app/(main)/location/components/VehicleStatusPanel/index.tsx
  app/(main)/location/components/ViewportVehicleList/index.tsx
  app/(main)/location/styles.css.ts
  app/(main)/route/components/MapSection/index.tsx
  app/(main)/route/components/VehicleSearchSection/indext.tsx
  app/(main)/route/page.tsx
  components/domain/cluster/ClusterOverlay/index.tsx
  components/domain/cluster/VehicleOverlay/index.tsx
  components/domain/vehicle/AutoComplete/index.tsx
  components/domain/vehicle/AutoComplete/styles.css.ts
  components/domain/vehicle/VehicleMarker/index.tsx
  hooks/useAutoComplete.ts
  hooks/useCoordToAddress.ts
  hooks/useQueryParams.ts
  hooks/useVehicleDisclosure.ts
  hooks/useVehicleLocationSearch.ts
  lib/apis/vehicle.ts
  lib/services/vehicle.ts
  lib/utils/vehicle.ts
Labels: ✨ Feat

#206 [Design] 로그인 및 지도 페이지 모바일 반응형 구현
  app/(auth)/signin/styles.css.ts
  app/(main)/location/components/VehicleDetailCard/index.tsx
  app/(main)/location/components/VehicleDetailCard/styles.css.ts
  app/(main)/location/components/VehicleStatusItem/styles.css.ts
  app/(main)/location/components/VehicleStatusPanel/styles.css.ts
  app/(main)/location/components/ViewportVehicleList/index.tsx
  app/(main)/location/components/ViewportVehicleList/styles.css.ts
  app/(main)/route/components/RouteSearchSection/index.tsx
  app/(main)/route/components/RouteSearchSection/styles.css.ts
  app/not-found.styles.css.ts
  app/not-found.tsx
  components/common/Modal/styles.css.ts
  components/domain/map/Map/index.tsx
  components/domain/vehicle/AutoComplete/styles.css.ts
  components/layout/NavBar/NavItem/styles.css.ts
  components/layout/NavBar/styles.css.ts
  types/vehicle.ts
Labels: 🎨 Design

#208 [Feat] 다크모드 기능 구현
  app/(main)/dashboard/components/Calendar/styles.css.ts
  app/(main)/dashboard/components/InspectionStatus/styles.css.ts
  app/(main)/dashboard/components/NoticeListBoard/styles.css.ts
  app/(main)/dashboard/components/Ranking/styles.css.ts
  app/(main)/dashboard/components/VehicleStatusPanel/styles.css.ts
  app/(main)/dashboard/inspection/components/InspectionCard/styles.css.ts
  app/(main)/dashboard/inspection/components/InspectionStatusPanel/styles.css.ts
  app/(main)/dashboard/styles.css.ts
  app/(main)/log/[id]/daily/components/ControlBox/styles.css.ts
  app/(main)/log/[id]/daily/styles.css.ts
  app/(main)/log/[id]/styles.css.ts
  app/(main)/log/components/LogListItem/styles.css.ts
  app/(main)/log/styles.css.ts
  app/(main)/route/components/RouteSearchSection/styles.css.ts
  components/common/Accordion/styles.css.ts
  components/common/Breadcrumbs/styles.css.ts
  components/common/Button/RoundButton/style.css.ts
  components/common/Switch/index.tsx
  components/layout/NavBar/NavItem/index.tsx
  components/layout/NavBar/NavItem/styles.css.ts
  components/layout/NavBar/index.tsx
  components/layout/NavBar/styles.css.ts
  styles/global.css.ts
  styles/theme.css.ts
Labels: 💅🏻 Style, ✨ Feat

#210 [Fix] 위치조회 페이지 상태관리 로직 개선
  app/(auth)/signin/styles.css.ts
  app/(main)/dashboard/styles.css.ts
  app/(main)/location/components/MapSection/index.tsx
  app/(main)/location/components/VehicleDetailCard/index.tsx
  app/(main)/location/components/VehicleDetailCard/styles.css.ts
  app/(main)/location/components/VehicleSearchSection/indext.tsx
  app/(main)/location/components/VehicleSearchSection/styles.css.ts
  app/(main)/location/components/VehicleStatusPanel/styles.css.ts
  app/(main)/location/components/ViewportVehicleList/index.tsx
  app/(main)/location/components/ViewportVehicleList/styles.css.ts
  app/(main)/route/Route.tsx
  app/(main)/route/components/RouteSearchSection/index.tsx
  app/(main)/route/components/VehicleSearchSection/indext.tsx
  app/(main)/route/types/date.ts
  components/domain/cluster/VehicleOverlay/index.tsx
  components/domain/vehicle/AutoComplete/styles.css.ts
  components/domain/vehicle/VehicleMarker/index.tsx
  components/layout/NavBar/styles.css.ts
  hooks/useCluster.ts
  hooks/useMapControl.ts
  hooks/useMapStatus.ts
  hooks/useQueryParams.ts
  lib/utils/map.ts
Labels: 🐛 Fix

#207 [Feat] InspectionPage API 연동 및 SSE 기능 구현
  app/(main)/dashboard/components/InspectionStatus/index.tsx
  app/(main)/dashboard/components/InspectionStatus/styles.css.ts
  app/(main)/dashboard/inspection/Inspection.tsx
  app/(main)/dashboard/inspection/components/InspectionCard/index.tsx
  app/(main)/dashboard/inspection/components/InspectionCard/styles.css.ts
  app/(main)/dashboard/inspection/components/InspectionStatusPanel/index.tsx
  app/(main)/dashboard/inspection/components/TabMenuWrapper/index.tsx
  app/(main)/dashboard/inspection/components/Tabs/index.tsx
  app/(main)/dashboard/inspection/hooks/useInspectionStatusData.ts
  app/(main)/dashboard/inspection/hooks/useStatusPanelData.ts
  app/(main)/dashboard/inspection/page.tsx
  app/(main)/dashboard/inspection/styles.css.ts
  app/(main)/dashboard/page.tsx
  app/(main)/layout.tsx
  app/(main)/log/[id]/daily/components/ControlBox/index.tsx
  app/(main)/log/[id]/daily/components/ControlBox/styles.css.ts
  app/(main)/log/[id]/daily/page.tsx
  components/common/Alarm/index.tsx
  components/common/InspectionStatusAlarm/index.tsx
  components/common/InspectionStatusAlarm/styles.css.ts
  components/common/InspectionStatusAlert/InspectionStatusModal.stories.tsx
  components/common/InspectionStatusAlert/index.tsx
  components/common/Skeleton/DailySkeleton/index.tsx
  components/common/Skeleton/DailySkeleton/styles.css.ts
  components/common/Skeleton/HeaderSkeleton/index.tsx
  components/common/Skeleton/PanelSkeleton/index.tsx
  components/common/Skeleton/PanelSkeleton/styles.css.ts
  components/common/Skeleton/RankingSkeleton/index.tsx
  components/common/Skeleton/RankingSkeleton/styles.css.ts
  components/common/TabMenu/index.tsx
  components/common/TabMenu/styles.css.ts
  constants/api.ts
  constants/inspection.ts
  hooks/useSubscribe.ts
  lib/apis/vehicle.ts
  types/apis/common.ts
  types/vehicle.ts
Labels: 🪐 API, ✨ Feat

#213 [Fix] SSE API 엔드포인트 수정
  hooks/useSubscribe.ts
Labels: 🐛 Fix

#215 [Fix] API 엔드포인트 수정
  hooks/useSubscribe.ts
Labels: 🐛 Fix

#214 [Feat] 자동완성 입력 Debounce 구현
  app/(main)/location/components/VehicleDetailCard/index.tsx
  app/(main)/location/components/VehicleSearchSection/indext.tsx
  app/(main)/route/Route.tsx
  app/(main)/route/components/MapSection/index.tsx
  app/(main)/route/page.tsx
  app/(main)/route/styles.css.ts
  components/domain/route/.gitkeep
  components/domain/vehicle/LiveMarker/index.tsx
  constants/map.ts
  hooks/useAutoComplete.ts
  hooks/useLiveRoute.ts
  hooks/useVehicleDisclosure.ts
  lib/apis/route.ts
  lib/utils/math.ts
  mock/live_routes copy.json
  mock/live_routes.json
  stores/useVehicleVisibleStore.ts
  types/route.ts
Labels: ✨ Feat

#217 [Fix] InspectionStatusAlarm 닫기 기능 제거
  components/common/Alarm/index.tsx
  components/common/InspectionStatusAlarm/index.tsx
  components/common/InspectionStatusAlarm/styles.css.ts
  components/common/SideFooter/index.tsx
  hooks/useSubscribe.ts
Labels: 🐛 Fix

#218 [Feat] 실시간 경로조회 기능 구현
  app/(main)/location/components/MapSection/index.tsx
  app/(main)/location/page.tsx
  app/(main)/route/Route.tsx
  app/(main)/route/components/DateRangeSection/index.tsx
  app/(main)/route/components/MapSection/index.tsx
  app/(main)/route/components/RouteSearchButton/index.tsx
  app/(main)/route/components/RouteSearchSection/index.tsx
  app/(main)/route/components/RouteSearchSection/styles.css.ts
  app/(main)/route/components/VehicleSearchSection/indext.tsx
  app/(main)/route/page.tsx
  components/common/Skeleton/MapSkeleton/index.tsx
  components/common/Skeleton/MapSkeleton/styles.css.ts
  components/domain/map/Map/index.tsx
  components/domain/vehicle/AutoComplete/index.tsx
  constants/map.ts
  hooks/useAutoComplete.ts
  hooks/useLiveRoute.ts
  hooks/useQueryParams.ts
  lib/apis/route.ts
  lib/apis/vehicle.ts
  lib/utils/normalize.ts
  types/vehicle.ts
Labels: 🪐 API, ✨ Feat

#221 [Feat] InspectionPage 및 LogPage 페이지네이션 기능 구현
  app/(main)/dashboard/components/InspectionStatus/index.tsx
  app/(main)/dashboard/components/InspectionStatus/styles.css.ts
  app/(main)/dashboard/inspection/Inspection.tsx
  app/(main)/dashboard/inspection/components/InspectionStatusPanel/index.tsx
  app/(main)/dashboard/page.tsx
  app/(main)/log/Log.tsx
  app/(main)/log/page.tsx
  types/vehicle.ts
Labels: ✨ Feat

#223 [Fix] 실시간 이동 경로 조회 API 파라미터 수정
  app/(main)/location/components/VehicleDetailCard/index.tsx
  components/common/Modal/index.tsx
  lib/apis/route.ts
  lib/apis/vehicle.ts
Labels: 🐛 Fix

#226 [Feat] LiveMode 컴포넌트 구현
  .gitignore
  app/(main)/dashboard/inspection/Inspection.tsx
  app/(main)/dashboard/inspection/components/InspectionCard/index.tsx
  app/(main)/dashboard/inspection/components/InspectionStatusPanel/index.tsx
  app/(main)/log/[id]/page.tsx
  app/(main)/route/components/DateRangeSection/index.tsx
  app/layout.tsx
  certificates/cert.pem
  certificates/key.pem
  components/common/Alarm/index.tsx
  components/common/LiveMode/index.tsx
  components/common/LiveMode/styles.css.ts
  hooks/useSubscribe.ts
  public/icons/index.ts
  public/icons/navigate-icon.svg
Labels: ✨ Feat

#228 [Docs] README.md 작성
  README.md
Labels: 📄 Docs

#229 [Docs] README.md 작성
  README.md
Labels: 📄 Docs
