Repository Kernel360/KDEV3_monicar_FE, pull requests merged in 2025-01, with the labels that each got.

#23 [Feat] Badge 공통 컴포넌트 구현
  .github/.gitmessage
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  app/layout.tsx
  app/test/page.tsx
  app/test/styles.css.ts
  components/common/Badge/Badge.stories.tsx
  components/common/Badge/constants.ts
  components/common/Badge/index.tsx
  components/common/Badge/styles.css.ts
  components/common/Badge/types.ts
  components/common/Button/Button.css.ts
  components/common/Button/Button.stories.tsx
  components/common/Button/index.tsx
  components/common/Input/index.tsx
  components/common/NavBar/index.tsx
  styles/reset.css.ts
  styles/theme.css.ts
Labels: ✨ Feat

#24 [Feat] Header 공통 컴포넌트 구현
  .storybook/preview.ts
  app/layout.tsx
  app/page.tsx
  components/common/Button/BackButton/index.tsx
  components/common/Button/BackButton/styles.css.ts
  components/layout/Footer.tsx
  components/layout/Header.tsx
  components/layout/Header/Header.stories.tsx
  components/layout/Header/index.tsx
  components/layout/Header/styles.css.ts
  styles/font.css.ts
  styles/global.css.ts
  styles/index.ts
  styles/theme.css.ts
  styles/utils.css.ts
Labels: ✨ Feat

#25 [Feat] BaseInput 컴포넌트 및 Message 컴포넌트 구현
  .vscode/settings.json
  components/common/Input/BaseInput/BaseInput.stories.tsx
  components/common/Input/BaseInput/index.tsx
  components/common/Input/BaseInput/styles.css.ts
  components/common/Input/index.tsx
  components/common/Message/Message.stories.tsx
  components/common/Message/constants.ts
  components/common/Message/index.tsx
  components/common/Message/styles.css.ts
  components/common/Message/types.ts
  public/favicon.ico
  public/file.svg
  public/fonts/AirbnbCereal/AirbnbCereal_W_Bd.otf
  public/fonts/AirbnbCereal/AirbnbCereal_W_Bd.woff2
  public/fonts/AirbnbCereal/AirbnbCereal_W_Bk.otf
  public/fonts/AirbnbCereal/AirbnbCereal_W_Bk.woff2
  public/fonts/AirbnbCereal/AirbnbCereal_W_Blk.otf
  public/fonts/AirbnbCereal/AirbnbCereal_W_Blk.woff2
  public/fonts/AirbnbCereal/AirbnbCereal_W_Lt.otf
  public/fonts/AirbnbCereal/AirbnbCereal_W_Lt.woff2
  public/fonts/AirbnbCereal/AirbnbCereal_W_Md.otf
  public/fonts/AirbnbCereal/AirbnbCereal_W_Md.woff2
  public/fonts/AirbnbCereal/AirbnbCereal_W_XBd.otf
  public/fonts/AirbnbCereal/AirbnbCereal_W_XBd.woff2
  public/globe.svg
  public/icons/back-icon.svg
  public/icons/black-alert-icon.svg
  public/icons/black-search-icon.svg
  public/text-logo.png
  public/vercel.svg
  public/window.svg
Labels: ✨ Feat

#27 [Feat] SideNavBar 공통 컴포넌트 구현
  .storybook/preview.ts
  .vscode/settings.json
  app/layout.tsx
  components/common/NavBar/index.tsx
  components/layout/Navigation/SideNavBar/NavItem/NavItem.stories.tsx
  components/layout/Navigation/SideNavBar/NavItem/index.tsx
  components/layout/Navigation/SideNavBar/NavItem/styles.css.ts
  components/layout/Navigation/SideNavBar/SideNavBar.stories.tsx
  components/layout/Navigation/SideNavBar/index.tsx
  components/layout/Navigation/SideNavBar/styles.css.ts
  config/constant.ts
  constants/navigation.ts
  public/icons/home-icon.svg
  public/next.svg
  styles/index.ts
  styles/layout.css.ts
  styles/reset.css.ts
  styles/theme.css.ts
  styles/utils.css.ts
Labels: ✨ Feat

#28 [Feat] SignInInput 공통 컴포넌트 구현
  app/layout.tsx
  app/page.tsx
  components/common/Input/BaseInput/BaseInput.stories.tsx
  components/common/Input/BaseInput/index.tsx
  components/common/Input/BaseInput/styles.css.ts
  components/common/Input/SignInInput/SignInInput.stories.tsx
  components/common/Input/SignInInput/index.tsx
  components/common/Input/SignInInput/styles.css.ts
  components/common/Message/Message.stories.tsx
  components/common/Message/index.tsx
  components/common/Message/styles.css.ts
  components/common/Message/types.ts
  components/common/Switch/index.tsx
  components/common/Switch/styles.css.ts
  components/layout/Header/Header.stories.tsx
  components/layout/Navigation/SideNavBar/index.tsx
  components/layout/Navigation/SideNavBar/styles.css.ts
  styles/font.css.ts
  styles/layout.css.ts
Labels: ✨ Feat

#33 [Style] Navigation 공통 컴포넌트 모바일 반응형 작업
  app/page.tsx
  components/layout/Navigation/SideNavBar/NavItem/styles.css.ts
  components/layout/Navigation/SideNavBar/styles.css.ts
Labels: 💅🏻 Style

#29 [Feat] Modal 공통 컴포넌트 구현
  app/hooks/.gitkeep
  app/hooks/useModal.ts
  app/page.tsx
  components/common/Modal/Modal.stories.tsx
  components/common/Modal/index.tsx
  components/common/Modal/styles.css.ts
  styles/layout.css.ts
Labels: ✨ Feat

#30 [Feat] BaseButton 및 RoundButton 공통 컴포넌트 구현
  app/page.tsx
  components/common/Button/BaseButton/BaseButton.stories.tsx
  components/common/Button/BaseButton/index.tsx
  components/common/Button/BaseButton/style.css.ts
  components/common/Button/Button.css.ts
  components/common/Button/Button.stories.tsx
  components/common/Button/RoundButton/RoundButton.stories.tsx
  components/common/Button/RoundButton/index.tsx
  components/common/Button/RoundButton/style.css.tsx
  components/common/Button/index.tsx
  components/layout/Header/index.tsx
  components/layout/NavBar/index.tsx
  constants/navigation.ts
  package.json
  public/icons/home-icon.svg
  public/icons/list-icon.svg
  public/icons/pie-chart-icon.svg
  public/icons/pointer-icon.svg
  public/icons/send-icon.svg
  styles/theme.css.ts
  yarn.lock
Labels: ✨ Feat

#40 [Design] 위치 조회 페이지 퍼블리싱
  .github/.gitmessage
  app/(dashboard)/history/page.tsx
  app/(dashboard)/layout.tsx
  app/(dashboard)/location/LocationMap/index.tsx
  app/(dashboard)/location/components/Map/index.tsx
  app/(dashboard)/location/components/VehicleStatus/index.tsx
  app/(dashboard)/location/components/VehicleStatus/styles.css.ts
  app/(dashboard)/location/page.tsx
  app/(dashboard)/location/styles.css.ts
  app/(dashboard)/page.tsx
  components/common/Input/BaseInput/index.tsx
  components/common/Input/SearchInput/styles.css.ts
  constants/navigation.ts
  hooks/useKakaoLoader.tsx
  hooks/useModal.ts
  package.json
  styles/layout.css.ts
  yarn.lock
Labels: 🎨 Design

#39 [Refactor] 공통 컴포넌트 리팩토링 개선 작업
  .github/.gitmessage
  app/layout.tsx
  components/common/Button/BaseButton/BaseButton.stories.tsx
  components/common/Button/BaseButton/index.tsx
  components/common/Button/BaseButton/style.css.ts
  components/common/Button/RoundButton/RoundButton.stories.tsx
  components/common/Button/RoundButton/index.tsx
  components/common/Button/RoundButton/style.css.tsx
  components/common/Button/SquareButton/SquareButton.stories.tsx
  components/common/Button/SquareButton/index.tsx
  components/common/Button/SquareButton/style.css.tsx
  components/common/Input/BaseInput/styles.css.ts
  components/common/Input/SearchInput/SearchInput.stories.tsx
  components/common/Input/SignInInput/styles.css.ts
  components/common/Modal/Modal.stories.tsx
  components/common/Modal/constants.ts
  components/common/Modal/index.tsx
  components/common/Modal/styles.css.ts
  components/common/Modal/types.ts
  next.config.mjs
  package.json
  public/icons/black-car-icon.svg
  public/icons/blue-car-icon.svg
  public/icons/clear-icon.svg
  public/icons/index.ts
  public/icons/mini-black-car-icon.svg
  public/icons/mini-blue-car-icon.svg
  public/icons/mini-red-car-icon.svg
  public/icons/mini-white-car-icon.svg
  public/icons/red-alert-icon.svg
  public/icons/red-car-icon.svg
  public/icons/right-icon.svg
  public/icons/white-alarm-icon.svg
  public/icons/white-bell-icon.svg
  public/icons/white-car-icon.svg
  public/icons/white-on-button-icon.svg
  styles/theme.css.ts
  tsconfig.json
  types/svg.d.ts
  yarn.lock
Labels: 🔨 Refactor

#42 [Design] 경로 조회 페이지 퍼블리싱
  app/(dashboard)/location/page.tsx
  app/(dashboard)/location/styles.css.ts
  app/(dashboard)/route/RouteList/index.tsx
  app/(dashboard)/route/components/RouteSearchPanel/DateTimeSelect/constants.ts
  app/(dashboard)/route/components/RouteSearchPanel/DateTimeSelect/index.tsx
  app/(dashboard)/route/components/RouteSearchPanel/DateTimeSelect/styles.css.ts
  app/(dashboard)/route/components/RouteSearchPanel/index.tsx
  app/(dashboard)/route/components/RouteSearchPanel/styles.css.ts
  app/(dashboard)/route/page.tsx
  app/(dashboard)/route/styles.css.ts
  app/layout.tsx
  components/common/Button/BaseButton/index.tsx
  components/common/Button/RoundButton/style.css.tsx
  components/common/Button/SquareButton/index.tsx
  components/common/Button/SquareButton/style.css.tsx
  components/common/Input/BaseInput/index.tsx
  components/common/Input/BaseInput/styles.css.ts
  components/common/Input/SearchInput/SearchInput.stories.tsx
  components/common/Input/SearchInput/index.tsx
  components/common/Input/SearchInput/styles.css.ts
  constants/navigation.ts
  hooks/useKakaoLoader.ts
  package.json
  postcss.config.cjs
  styles/theme.css.ts
  yarn.lock
Labels: 🎨 Design

#45 [Feat] 카카오맵 API를 활용한 Polyline 기능 구현
  app/(dashboard)/location/components/Map/index.tsx
  app/(dashboard)/route/page.tsx
  components/common/Input/SearchInput/index.tsx
  eslint.config.mjs
  mock/routes.json
  mock/vehicleItemSearchOK.json
  mock/vehicleNumberOK.json
  styles/reset.css.ts
  types/.gitkeep
  types/location.ts
Labels: 🐛 Fix, ✨ Feat

#51 [Feat] 위치조회 페이지 개별 차량 조회 기능 구현
  app/(dashboard)/location/components/Map/index.tsx
  app/(dashboard)/location/page.tsx
  app/(dashboard)/location/styles.css.ts
  app/(dashboard)/route/page.tsx
  components/common/Input/BaseInput/index.tsx
  components/common/Input/SearchInput/index.tsx
  components/common/Modal/Modal.stories.tsx
  components/common/Modal/index.tsx
  components/common/Modal/types.ts
  constants/map.ts
  eslint.config.mjs
  hooks/useMapControl.ts
  hooks/useModal.ts
  hooks/useSearchSingleVehicle.ts
  lib/validation.ts
  mock/single_vehicle_search_ok.json
  mock/vehicleItemSearchOK.json
  mock/vehicle_route_data.json
  types/ui.ts
  types/vehicle.ts
Labels: ✨ Feat

#54 [Setting] Axios 인스턴스 및 인터셉터 설정
  constants/api.ts
  lib/apis/client.ts
  lib/apis/index.ts
  lib/apis/interceptors.ts
  lib/apis/vehicle.ts
  package.json
  yarn.lock
Labels: ✨ Feat, ⚙️ Setting

#55 [Feat] Switch 공통 컴포넌트 구현
  components/common/Switch/index.tsx
  components/common/Switch/styles.css.ts
Labels: ✨ Feat

#53 [Feat] VehicleRegisterForm 컴포넌트 작업
  app/(dashboard)/log/VehicleRegisterForm/index.tsx
  app/(dashboard)/log/VehicleRegisterForm/styles.css.ts
  app/(dashboard)/log/page.tsx
  components/common/Input/SearchInput/index.tsx
Labels: ✨ Feat

#47 [Feat] LogPage, HistoryPage 퍼블리싱 및 리스트 컴포넌트 작업
  app/(dashboard)/history/components/ListItem/index.tsx
  app/(dashboard)/history/components/ListItem/styles.css.ts
  app/(dashboard)/history/page.tsx
  app/(dashboard)/history/styles.css.ts
  app/(dashboard)/log/VehicleList/index.tsx
  app/(dashboard)/log/components/ListItem/index.tsx
  app/(dashboard)/log/components/ListItem/styles.css.ts
  app/(dashboard)/log/components/VehicleRegisterForm/index.tsx
  app/(dashboard)/log/components/VehicleRegisterForm/styles.css.ts
  app/(dashboard)/log/page.tsx
  app/(dashboard)/log/styles.css.ts
  components/common/Badge/styles.css.ts
  components/common/Button/BaseButton/style.css.ts
  components/common/Button/RoundButton/index.tsx
  components/common/Button/RoundButton/style.css.tsx
  components/common/Button/SquareButton/index.tsx
  components/common/Button/SquareButton/style.css.tsx
  components/common/Input/BaseInput/index.tsx
  components/domain/vehicle/ListHeader/index.tsx
  components/domain/vehicle/ListHeader/styles.css.ts
  components/domain/vehicle/SearchField/index.tsx
  components/domain/vehicle/SearchField/styles.css.ts
  styles/theme.css.ts
  types/history.ts
  types/log.ts
Labels: ✨ Feat, 🎨 Design

#57 [Design] 차량등록 페이지 퍼블리싱
  app/(dashboard)/log/components/VehicleRegisterForm/index.tsx
  app/(dashboard)/log/register/page.tsx
  app/(dashboard)/log/register/styles.css.ts
  components/common/Button/RoundButton/style.css.ts
  components/common/Button/SquareButton/style.css.ts
Labels: 🎨 Design

#62 [Feat] VehicleLayout 컴포넌트 구현
  components/domain/vehicle/VehicleLayout/index.tsx
  components/domain/vehicle/VehicleLayout/styles.css.ts
Labels: ✨ Feat

#69 [Design] Dashboard 페이지 퍼블리싱
  .github/.gitmessage
  app/components/InspectionStatus/index.tsx
  app/components/InspectionStatus/styles.css.ts
  app/components/NoticeBoard/index.tsx
  app/components/NoticeBoard/styles.css.ts
  app/components/VehicleStatus/index.tsx
  app/components/VehicleStatus/styles.css.ts
  app/components/calendar/index.tsx
  app/components/calendar/styles.css.ts
  app/page.tsx
  app/styles.css.ts
  public/icons/index.ts
  public/icons/white-alert-icon.svg
  public/icons/white-check-icon.svg
  public/images/notice-1.jpg
  public/images/notice-2.jpg
  public/images/notice-3.jpg
  styles/global.css.ts
  styles/theme.css.ts
Labels: 🎨 Design

#70 [Feat] 개별 차량 상세 정보 카드 구현
  app/(dashboard)/location/components/VehicleDetailsCard/index.tsx
  app/(dashboard)/location/components/VehicleDetailsCard/styles.css.ts
  app/(dashboard)/location/components/VehicleMarker/index.tsx
  app/(dashboard)/location/components/VehicleMarker/styles.css.ts
  app/(dashboard)/location/components/VehicleStatus/styles.css.ts
  app/(dashboard)/location/page.tsx
  app/(dashboard)/location/styles.css.ts
  app/(dashboard)/route/page.tsx
  app/page.tsx
  components/domain/map/Map/index.tsx
  hooks/useCoordToAddress.ts
  hooks/useSearchSingleVehicle.ts
  lib/apis/vehicle.ts
  lib/utils/date.ts
  lib/utils/map.ts
  types/vehicle.ts
Labels: ✨ Feat, 🎨 Design

#63 [Feat] 경로조회 [차량 검색 > 기간 검색] 기능구현
  .github/.gitmessage
  app/(dashboard)/route/components/RouteSearchPanel/DateTimeSelect/constants.ts
  app/(dashboard)/route/components/RouteSearchPanel/DateTimeSelect/index.tsx
  app/(dashboard)/route/components/RouteSearchPanel/DateTimeSelect/styles.css.ts
  app/(dashboard)/route/components/RouteSearchPanel/index.tsx
  app/(dashboard)/route/components/RouteSearchPanel/styles.css.ts
  app/(dashboard)/route/page.tsx
  app/(dashboard)/route/types/date.ts
  components/common/Button/BaseButton/style.css.ts
  components/common/Modal/Modal.stories.tsx
  components/common/Modal/types.ts
  components/layout/NavBar/NavItem/index.tsx
  components/layout/NavBar/NavItem/styles.css.ts
  components/layout/NavBar/index.tsx
  constants/map.ts
  constants/ui.ts
  hooks/useMapControl.ts
  hooks/useSearchSingleVehicle.ts
  hooks/useSearchVehicle.ts
  lib/apis/vehicle.ts
  lib/utils/date.ts
  lib/utils/validation.ts
  lib/validation.ts
  package.json
  types/location.ts
  types/map.ts
  types/vehicle.ts
  yarn.lock
Labels: 🪐 API, ✨ Feat

#77 [Feat] LinkButton 공통 컴포넌트 구현
  app/(dashboard)/log/[id]/page.tsx
  components/common/Button/BaseButton/index.tsx
  components/common/Button/BaseButton/styles.css.ts
  components/common/Button/LinkButton/index.tsx
  components/common/Button/LinkButton/styles.css.ts
Labels: ✨ Feat

#74 [Design] 운행일지 페이지 퍼블리싱 작업
  app/(dashboard)/log/[id]/page.tsx
  app/(dashboard)/log/[id]/styles.css.ts
  app/page.tsx
  components/common/Table/index.tsx
Labels: 🎨 Design

#76 [Feat] Breadcrumb 공통 컴포넌트 생성
  components/common/Breadcrumb/Breadcrumb.stories.tsx
  components/common/Breadcrumb/index.tsx
  components/common/Breadcrumb/styles.css.ts
  components/common/Breadcrumb/type.ts
Labels: ✨ Feat

#75 [Refactor] NavBar 컴포넌트 수정 및 LogPage/HistoryPage 통합
  .github/.gitmessage
  app/(dashboard)/history/components/ListItem/index.tsx
  app/(dashboard)/history/components/ListItem/styles.css.ts
  app/(dashboard)/history/page.tsx
  app/(dashboard)/history/styles.css.ts
  app/(dashboard)/log/components/ListItem/index.tsx
  app/(dashboard)/log/components/ListItem/styles.css.ts
  app/(dashboard)/log/page.tsx
  components/domain/vehicle/VehicleLayout/index.tsx
  components/domain/vehicle/VehicleLayout/styles.css.ts
  components/layout/NavBar/NavItem/index.tsx
  constants/navigation.ts
  public/icons/home-icon.svg
  public/icons/list-icon.svg
  public/icons/pin-icon.svg
  public/icons/pointer-icon.svg
  public/icons/red-car-icon.svg
  types/log.ts
Labels: 🔨 Refactor

#82 [Design] NoticePage 퍼블리싱
  app/(dashboard)/notice/page.tsx
  app/(dashboard)/notice/styles.css.ts
  components/common/Breadcrumb/constants.ts
  components/common/Breadcrumb/index.tsx
  components/common/Breadcrumb/types.ts
Labels: 🎨 Design

#83 [Style] LogPage 변경된 디자인 적용
  app/(dashboard)/log/page.tsx
  app/(dashboard)/log/styles.css.ts
  components/common/Button/RoundButton/style.css.ts
  components/domain/vehicle/SearchField/index.tsx
  components/domain/vehicle/SearchField/styles.css.ts
  public/icons/green-excel-icon.svg
  public/icons/index.ts
  public/icons/white-add-icon.svg
  public/icons/white-trash-icon.svg
Labels: 💅🏻 Style

#86 [Fix] 스토리북 배포 오류 문제 해결
  components/layout/NavBar/NavBar.stories.tsx
Labels: 🐛 Fix

#89 [Design] 로그인 페이지 레이아웃 및 UI 구현
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signin/styles.css.ts
  app/(main)/dashboard/components/Calendar/index.tsx
  app/(main)/dashboard/components/Calendar/styles.css.ts
  app/(main)/dashboard/components/InspectionStatus/index.tsx
  app/(main)/dashboard/components/InspectionStatus/styles.css.ts
  app/(main)/dashboard/components/NoticeBoard/index.tsx
  app/(main)/dashboard/components/NoticeBoard/styles.css.ts
  app/(main)/dashboard/components/VehicleStatus/index.tsx
  app/(main)/dashboard/components/VehicleStatus/styles.css.ts
  app/(main)/dashboard/notice/page.tsx
  app/(main)/dashboard/notice/styles.css.ts
  app/(main)/dashboard/page.tsx
  app/(main)/dashboard/styles.css.ts
  app/(main)/layout.tsx
  app/(main)/location/LocationPage.tsx
  app/(main)/location/components/VehicleDetailsCard/index.tsx
  app/(main)/location/components/VehicleDetailsCard/styles.css.ts
  app/(main)/location/components/VehicleMarker/index.tsx
  app/(main)/location/components/VehicleMarker/styles.css.ts
  app/(main)/location/components/VehicleStatus/index.tsx
  app/(main)/location/components/VehicleStatus/styles.css.ts
  app/(main)/location/page.tsx
  app/(main)/location/styles.css.ts
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/styles.css.ts
  app/(main)/log/components/ListItem/index.tsx
  app/(main)/log/components/ListItem/styles.css.ts
  app/(main)/log/components/VehicleRegisterForm/index.tsx
  app/(main)/log/components/VehicleRegisterForm/styles.css.ts
  app/(main)/log/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/register/styles.css.ts
  app/(main)/log/styles.css.ts
  app/(main)/page.tsx
  app/(main)/route/RoutePage.tsx
  app/(main)/route/components/RouteSearchPanel/DateTimeSelect/constants.ts
  app/(main)/route/components/RouteSearchPanel/DateTimeSelect/index.tsx
  app/(main)/route/components/RouteSearchPanel/DateTimeSelect/styles.css.ts
  app/(main)/route/components/RouteSearchPanel/index.tsx
  app/(main)/route/components/RouteSearchPanel/styles.css.ts
  app/(main)/route/page.tsx
  app/(main)/route/styles.css.ts
  app/(main)/route/types/date.ts
  app/layout.tsx
  components/common/Button/BaseButton/index.tsx
  components/common/Input/SignInInput/index.tsx
  components/common/Input/SignInInput/styles.css.ts
  lib/utils/validation.ts
  public/images/sign-in-car.png
  public/images/sign-in-map.png
  public/white-text-logo.png
Labels: 🎨 Design

#91 [Feat] LogPage 기능 구현 및 API 연동
  app/(main)/log/[id]/page.tsx
  app/(main)/log/components/ListItem/index.tsx
  app/(main)/log/components/ListItem/styles.css.ts
  app/(main)/log/constants.ts
  app/(main)/log/hooks/useLogData.ts
  app/(main)/log/page.tsx
  app/(main)/log/register/page.tsx
  app/(main)/log/styles.css.ts
  app/(main)/log/types.ts
  app/(main)/log/utils/excel.ts
  components/common/Badge/Badge.stories.tsx
  components/common/Badge/constants.ts
  components/common/Badge/styles.css.ts
  components/common/Breadcrumb/index.tsx
  components/common/Breadcrumb/styles.css.ts
  components/domain/vehicle/ControlBar/index.tsx
  components/domain/vehicle/ControlBar/styles.css.ts
  components/domain/vehicle/SearchField/index.tsx
  components/domain/vehicle/SearchField/styles.css.ts
  package.json
  public/www.freepik.com:.webloc
  styles/theme.css.ts
  types/history.ts
  types/log.ts
  yarn.lock
Labels: 🪐 API, ✨ Feat

#99 [Feat] 차량 시동 현황 Progress 컴포넌트 구현
  app/(main)/location/LocationPage.tsx
  app/(main)/location/components/VehicleStatus/index.tsx
  app/(main)/location/components/VehicleStatus/styles.css.ts
  app/(main)/location/components/VehicleStatusItem/index.tsx
  app/(main)/location/components/VehicleStatusItem/styles.css.ts
  app/(main)/location/components/VehicleStatusPanel/index.tsx
  app/(main)/location/components/VehicleStatusPanel/styles.css.ts
Labels: ✨ Feat

#96 [Refactor] API GET 요청 로직 분리 작업
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/styles.css.ts
  app/(main)/log/hooks/useLogData.ts
  app/(main)/log/page.tsx
  app/(main)/log/types.ts
  constants/api.ts
  hooks/useData.ts
  types/history.ts
Labels: 🪐 API, 🔨 Refactor

#100 [Feat] 위치조회 > 개별 차량 검색 / 상세 정보 조회 API 연동 및 데이터 정규화
  app/(main)/location/LocationPage.tsx
  app/(main)/location/components/VehicleDetailsCard/index.tsx
  app/(main)/location/components/VehicleMarker/index.tsx
  hooks/useSearchSingleVehicle.ts
  hooks/useSearchVehicle.ts
  lib/apis/vehicle.ts
  lib/utils/normalize.ts
  lib/utils/string.ts
  lib/utils/validation.ts
  types/vehicle.ts
Labels: 🪐 API, ✨ Feat

#102 [Feat] DetailPage 기능 구현
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/records/page.tsx
  app/(main)/log/[id]/styles.css.ts
  components/common/ControlLayout/index.tsx
  components/common/ControlLayout/styles.css.ts
  components/domain/vehicle/ControlBar/index.tsx
  package.json
  styles/index.ts
  styles/reset.css.ts
  yarn.lock
Labels: ✨ Feat

#103 [Fix] Next.js HMR 스타일 초기화 문제 해결
  app/(main)/dashboard/components/InspectionStatus/index.tsx
  app/(main)/location/LocationPage.tsx
  app/(main)/location/components/MapSection/index.tsx
  app/(main)/location/components/VehicleStatus/styles.css.ts
  app/(main)/location/page.tsx
  components/common/Modal/index.tsx
  components/domain/map/Map/index.tsx
  next.config.mjs
Labels: 🐛 Fix

#105 [Feat] 차량현황 조회 API 연동 및 기능구현
  app/(main)/location/components/VehicleStatusItem/index.tsx
  app/(main)/location/components/VehicleStatusItem/styles.css.ts
  app/(main)/location/components/VehicleStatusPanel/index.tsx
  lib/apis/vehicle.ts
  next.config.mjs
Labels: 🪐 API, ✨ Feat

#106 [Feat] InspectionStatusModal 컴포넌트 구현
  app/(main)/dashboard/components/InspectionStatus/styles.css.ts
  app/(main)/log/[id]/records/page.tsx
  components/common/Button/BaseButton/styles.css.ts
  components/common/InspectionStatusModal/InspectionStatusModal.stories.tsx
  components/common/InspectionStatusModal/index.tsx
  components/common/InspectionStatusModal/styles.css.ts
Labels: ✨ Feat

#114 [Feat] DetailPage API 연동
  app/(main)/log/[id]/hooks/useDetailData.ts
  app/(main)/log/[id]/page.tsx
  app/(main)/log/[id]/types.ts
Labels: 🪐 API

#120 [Feat] ExcelButton 공통 컴포넌트 구현
  app/(main)/log/[id]/daily/page.tsx
  app/(main)/log/[id]/daily/styles.css.ts
  app/(main)/log/[id]/page.tsx
  components/common/Button/ExcelButton/index.tsx
  components/common/Button/ExcelButton/styles.css.ts
  components/domain/vehicle/ControlBar/index.tsx
  components/domain/vehicle/ControlBar/styles.css.ts
Labels: ✨ Feat, 🔨 Refactor

#123 [Fix] 프리뷰 URL CORS 문제 해결
  lib/apis/vehicle.ts
Labels: 🐛 Fix

#127 [Feat] 로그인 페이지 기능 구현
  app/(auth)/signin/page.tsx
  app/(auth)/signin/styles.css.ts
  app/(main)/location/components/VehicleStatusPanel/index.tsx
  app/(main)/location/page.tsx
  app/(main)/route/components/RouteSearchPanel/index.tsx
  components/common/Input/BaseInput/index.tsx
  components/common/Input/SearchInput/index.tsx
  components/common/Input/SignInInput/index.tsx
  components/common/Modal/styles.css.ts
  hooks/useAuth.ts
  hooks/useData.ts
  hooks/useSearchSingleVehicle.ts
  hooks/useSearchVehicle.ts
  lib/apis/auth.ts
  lib/apis/client.ts
  lib/apis/interceptors.ts
  lib/apis/vehicle.ts
  lib/utils/string.ts
  lib/utils/validation.ts
  middleware.ts
  package.json
  stores/useAuthStore.ts
  yarn.lock
Labels: 🪐 API, ✨ Feat

#126 [Feat] NoticePage API 연동
  app/(main)/dashboard/components/Calendar/styles.css.ts
  app/(main)/dashboard/components/NoticeBoard/index.tsx
  app/(main)/dashboard/components/NoticeListBoard/index.tsx
  app/(main)/dashboard/components/NoticeListBoard/styles.css.ts
  app/(main)/dashboard/notice/[id]/page.tsx
  app/(main)/dashboard/notice/[id]/styles.css.ts
  app/(main)/dashboard/notice/page.tsx
  app/(main)/dashboard/page.tsx
  app/(main)/dashboard/styles.css.ts
  lib/apis/notice.ts
  lib/utils/date.ts
  styles/layout.css.ts
  types/notice.ts
Labels: 🪐 API, ✨ Feat
